# Generated by Django 5.2.1 on 2025-06-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='timesheetitem',
            options={'verbose_name': 'Запись о рабочих часах', 'verbose_name_plural': 'Записи о рабочих часах'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(choices=[('analytic', 'Аналитик'), ('developer', 'Разработчик'), ('tester', 'Тестировщик')], default='developer', max_length=20, verbose_name='Должность'),
        ),
    ]
