# Generated by Django 5.2.1 on 2025-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_options_alter_timesheetitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(choices=[('active', 'активен'), ('stopped', 'приостановлен'), ('closed', 'завершен')], default='active', max_length=20, verbose_name='Статус проекта'),
        ),
    ]
