# Generated by Django 5.2.1 on 2025-06-20 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timesheet_items', to='main.project'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timesheet_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
